# Kustomization for ArgoCD deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: order-platform

resources:
  - namespace.yaml
  - kafka/zookeeper.yaml
  - kafka/kafka.yaml
  - kafka/kafka-ui.yaml
  - services/order-service.yaml
  - services/payment-service.yaml
  - services/stock-service.yaml
  - services/demo-ui.yaml
  - monitoring/prometheus-config.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana-config.yaml
  - monitoring/grafana.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: order-platform
  app.kubernetes.io/managed-by: argocd
